### This file is used to test the REST API endpoints

GET http://localhost:5000/
### Test Create Patient
POST http://localhost:5000/api/patients
Content-Type: application/json

{
    "firstName": "Golden",
    "lastName": "Tendekai",
    "email": "golden@mail.com",
    "phoneNumber": "0772142413",
    "role": "Patient",
    "password": "password"
}

### Test Create a doctor
POST http://localhost:5000/api/doctors
Content-Type: application/json

{
    "firstName": "Doctor",
    "lastName": "Test",
    "email": "doctor@test.com",
    "phoneNumber": "0772142413",
    "practice_number": "FB299883",
    "role": "Doctor",
    "password": "password"
}

### Test Login (doctor)
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "doctor@test.com",
    "password": "password"
}

### Test Login (Patient)
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "golden@mail.com",
    "password": "password"
}

### List all patients
GET http://localhost:5000/api/patients

### Read a patient by accountId
GET http://localhost:5000/api/patients/602f97e68ce0be07507156e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOTdlNjhjZTBiZTA3NTA3MTU2ZTUiLCJpYXQiOjE2MTM3Mzk1Mjl9.lyE51VXmU7K9vryI1xtK-iLsPOejk71k3ZPlfNAGZjg

### List all doctors
GET http://localhost:5000/api/doctors

### Read a doctor by accountId
GET http://localhost:5000/api/doctors/602f9a36be4d89387c1756f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOWEzNmJlNGQ4OTM4N2MxNzU2ZjYiLCJpYXQiOjE2MTM3NDA5MDd9.yxioVPNdV3pphXIbCzlzoGW1w8mzjvMxepmbRXPkISk

### Read a doctor by accountId
POST http://localhost:5000/api/doctors/602f9a36be4d89387c1756f6/activate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOWEzNmJlNGQ4OTM4N2MxNzU2ZjYiLCJpYXQiOjE2MTM3NDA5MDd9.yxioVPNdV3pphXIbCzlzoGW1w8mzjvMxepmbRXPkISk

{
    "physical_address": "The address",
    "affiliations": "Affiliations",
    "brief_introduction": "This is the intro"
}

### Schedule an appointment
POST http://localhost:5000/api/appointment/by/602f97e68ce0be07507156e5/with/602f9a36be4d89387c1756f7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOTdlNjhjZTBiZTA3NTA3MTU2ZTUiLCJpYXQiOjE2MTM3Mzk1Mjl9.lyE51VXmU7K9vryI1xtK-iLsPOejk71k3ZPlfNAGZjg

{
    "start_time": "2021-02-21T05:43:52.815Z",
    "end_time": "2021-02-21T07:43:52.815Z"
}

### list appointments by patient
GET http://localhost:5000/api/appointments/patient/602f97e68ce0be07507156e5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOTdlNjhjZTBiZTA3NTA3MTU2ZTUiLCJpYXQiOjE2MTM3Mzk1Mjl9.lyE51VXmU7K9vryI1xtK-iLsPOejk71k3ZPlfNAGZjg

### list appointments by doctor
GET http://localhost:5000/api/appointments/doctor/602f9a36be4d89387c1756f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDJmOWEzNmJlNGQ4OTM4N2MxNzU2ZjYiLCJpYXQiOjE2MTM3NDA5MDd9.yxioVPNdV3pphXIbCzlzoGW1w8mzjvMxepmbRXPkISk





